name: SAST

on:
  push:
    branches: [main, feature/integracion, fases6y7]
  pull_request:
    branches: [main, feature/integracion, fases6y7]

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Scan lab1
        run: semgrep scan --config=auto --error --severity=ERROR lab1/
